CREATE TABLE [dbo].[STRATO_PITCHING_DATA](
	[Rk] smallint NULL,
	[Name] varchar(50) NULL,
	[Year] smallint NULL,
	[Age] tinyint NULL,
	[Tm] varchar(5) NULL,
	[Lg] varchar(5) NULL,
	[W] tinyint NULL,
	[L] tinyint NULL,
	[W-L%] numeric(9, 3) NULL,
	[ERA] numeric(9, 2) NULL,
	[G] smallint NULL,
	[GS] smallint NULL,
	[GF] smallint NULL,
	[CG] smallint NULL,
	[SHO] smallint NULL,
	[SV] tinyint NULL,
	[IP] numeric(9, 1) NULL,
	[H] smallint NULL,
	[R] smallint NULL,
	[ER] smallint NULL,
	[HR] smallint NULL,
	[BB] smallint NULL,
	[IBB] smallint NULL,
	[SO] smallint NULL,
	[HBP] smallint NULL,
	[BK] smallint NULL,
	[WP] smallint NULL,
	[BF] smallint NULL,
	[ERA+] smallint NULL,
	[FIP] numeric(9, 2) NULL,
	[WHIP] numeric(9, 3) NULL,
	[H9] numeric(9, 1) NULL,
	[HR9] numeric(9, 1) NULL,
	[BB9] numeric(9, 1) NULL,
	[SO9] numeric(9, 1) NULL,
	[SO/W] numeric(9, 2) NULL,
	[Player_CDE] varchar(15) NULL,
	[G-vsLHB] smallint NULL,
	[PA-vsLHB] smallint NULL,
	[AB-vsLHB] smallint NULL,
	[R-vsLHB] smallint NULL,
	[H-vsLHB] smallint NULL,
	[2B-vsLHB] smallint NULL,
	[3B-vsLHB] tinyint NULL,
	[HR-vsLHB] tinyint NULL,
	[SB-vsLHB] tinyint NULL,
	[CS-vsLHB] tinyint NULL,
	[BB-vsLHB] smallint NULL,
	[SO-vsLHB] smallint NULL,
	[SO/W-vsLHB] numeric(9, 2) NULL,
	[BA-vsLHB] numeric(9, 3) NULL,
	[OBP-vsLHB] numeric(9, 3) NULL,
	[SLG-vsLHB] numeric(9, 3) NULL,
	[OPS-vsLHB] numeric(9, 3) NULL,
	[TB-vsLHB] smallint NULL,
	[GDP-vsLHB] smallint NULL,
	[HBP-vsLHB] smallint NULL,
	[SH-vsLHB] smallint NULL,
	[SF-vsLHB] smallint NULL,
	[IBB-vsLHB] smallint NULL,
	[ROE-vsLHB] smallint NULL,
	[BAbip-vsLHB] numeric(9, 3) NULL,
	[tOPS+-vsLHB] smallint NULL,
	[sOPS+-vsLHB] smallint NULL,
	[G-vsRHB] smallint NULL,
	[PA-vsRHB] smallint NULL,
	[AB-vsRHB] smallint NULL,
	[R-vsRHB] smallint NULL,
	[H-vsRHB] smallint NULL,
	[2B-vsRHB] smallint NULL,
	[3B-vsRHB] tinyint NULL,
	[HR-vsRHB] tinyint NULL,
	[SB-vsRHB] tinyint NULL,
	[CS-vsRHB] tinyint NULL,
	[BB-vsRHB] smallint NULL,
	[SO-vsRHB] smallint NULL,
	[SO/W-vsRHB] numeric(9, 2) NULL,
	[BA-vsRHB] numeric(9, 3) NULL,
	[OBP-vsRHB] numeric(9, 3) NULL,
	[SLG-vsRHB] numeric(9, 3) NULL,
	[OPS-vsRHB] numeric(9, 3) NULL,
	[TB-vsRHB] smallint NULL,
	[GDP-vsRHB] smallint NULL,
	[HBP-vsRHB] smallint NULL,
	[SH-vsRHB] smallint NULL,
	[SF-vsRHB] smallint NULL,
	[IBB-vsRHB] smallint NULL,
	[ROE-vsRHB] smallint NULL,
	[BAbip-vsRHB] numeric(9, 3) NULL,
	[tOPS+-vsRHB] smallint NULL,
	[sOPS+-vsRHB] smallint NULL
)
GO;
CREATE CLUSTERED INDEX [CI_Year] on [dbo].[STRATO_PITCHING_DATA] ([Year] ASC) WITH(DATA_COMPRESSION=PAGE);
GO;