CREATE TABLE [dbo].[STRATO_BATTING_DATA](
	[Rk] smallint NULL,
	[Name] varchar(50) NULL,
	[Year] smallint NULL,
	[Age] tinyint NULL,
	[Tm] varchar(5) NULL,
	[Lg] varchar(5) NULL,
	[G] smallint NULL,
	[PA] smallint NULL,
	[AB] smallint NULL,
	[R] smallint NULL,
	[H] smallint NULL,
	[2B] smallint NULL,
	[3B] tinyint NULL,
	[HR] tinyint NULL,
	[RBI] smallint NULL,
	[SB] smallint NULL,
	[CS] smallint NULL,
	[BB] smallint NULL,
	[SO] smallint NULL,
	[BA] numeric(9, 3) NULL,
	[OBP] numeric(9, 3) NULL,
	[SLG] numeric(9, 3) NULL,
	[OPS] numeric(9, 3) NULL,
	[OPS+] smallint NULL,
	[TB] smallint NULL,
	[GDP] smallint NULL,
	[HBP] smallint NULL,
	[SH] smallint NULL,
	[SF] smallint NULL,
	[IBB] smallint NULL,
	[Pos Summary] varchar(30) NULL,
	[Player_CDE] varchar(15) NULL,
	[G-vsLHP] tinyint NULL,
	[GS-vsLHP] tinyint NULL,
	[PA-vsLHP] smallint NULL,
	[AB-vsLHP] smallint NULL,
	[R-vsLHP] smallint NULL,
	[H-vsLHP] smallint NULL,
	[2B-vsLHP] smallint NULL,
	[3B-vsLHP] tinyint NULL,
	[HR-vsLHP] tinyint NULL,
	[RBI-vsLHP] smallint NULL,
	[SB-vsLHP] smallint NULL,
	[CS-vsLHP] tinyint NULL,
	[BB-vsLHP] smallint NULL,
	[SO-vsLHP] smallint NULL,
	[BA-vsLHP] numeric(9, 3) NULL,
	[OBP-vsLHP] numeric(9, 3) NULL,
	[SLG-vsLHP] numeric(9, 3) NULL,
	[OPS-vsLHP] numeric(9, 3) NULL,
	[TB-vsLHP] smallint NULL,
	[GDP-vsLHP] smallint NULL,
	[HBP-vsLHP] tinyint NULL,
	[SH-vsLHP] tinyint NULL,
	[SF-vsLHP] tinyint NULL,
	[IBB-vsLHP] tinyint NULL,
	[ROE-vsLHP] tinyint NULL,
	[BAbip-vsLHP] numeric(9, 3) NULL,
	[tOPS+-vsLHP] smallint NULL,
	[sOPS+-vsLHP] smallint NULL,
	[G-vsRHP] tinyint NULL,
	[GS-vsRHP] tinyint NULL,
	[PA-vsRHP] smallint NULL,
	[AB-vsRHP] smallint NULL,
	[R-vsRHP] smallint NULL,
	[H-vsRHP] smallint NULL,
	[2B-vsRHP] smallint NULL,
	[3B-vsRHP] tinyint NULL,
	[HR-vsRHP] tinyint NULL,
	[RBI-vsRHP] smallint NULL,
	[SB-vsRHP] smallint NULL,
	[CS-vsRHP] tinyint NULL,
	[BB-vsRHP] smallint NULL,
	[SO-vsRHP] smallint NULL,
	[BA-vsRHP] numeric(9, 3) NULL,
	[OBP-vsRHP] numeric(9, 3) NULL,
	[SLG-vsRHP] numeric(9, 3) NULL,
	[OPS-vsRHP] numeric(9, 3) NULL,
	[TB-vsRHP] smallint NULL,
	[GDP-vsRHP] smallint NULL,
	[HBP-vsRHP] tinyint NULL,
	[SH-vsRHP] tinyint NULL,
	[SF-vsRHP] tinyint NULL,
	[IBB-vsRHP] tinyint NULL,
	[ROE-vsRHP] tinyint NULL,
	[BAbip-vsRHP] numeric(9, 3) NULL,
	[tOPS+-vsRHP] smallint NULL,
	[sOPS+-vsRHP] smallint NULL
)
GO;
CREATE CLUSTERED INDEX [CI_YEAR] ON [dbo].[STRATO_BATTING_DATA] ([Year] ASC) WITH(DATA_COMPRESSION=PAGE);
GO;